snowflake_ci_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: RHPZJRX-ZN50394
      user: NALAJALAVENNELA
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: dbt_cli
      schema: dev
      threads: 5
