name: dbt CI

on:
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Setup profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          snowflake_ci_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
          " > ~/.dbt/profiles.yml

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt build
        run: dbt build